---
- name: Playbook
  hosts: localhost
  gather_facts: no
  connection: local

  tasks:
    - name: "Install mplayer"
      apt:
        name: mplayer
        state: present
    - name: "Install psutils"
      apt:
        name: psutils
        state: present
